jobs:
  test:
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out repository
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Cache maven repository
      uses: actions/cache@v2
      with:
        key: ${{ matrix.arch }}-${{ runner.os }}-maven-${{ matrix.java }}-${{ hashFiles('**/pom.xml')
          }}
        path: '~/.m2/repository

          '
        restore-keys: '${{ matrix.arch }}-${{ runner.os }}-maven-${{ matrix.java }}

          ${{ matrix.arch }}-${{ runner.os }}-maven

          '
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v1
      with:
        architecture: ${{ matrix.arch }}
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Test with Maven
      run: mvn verify -B --file pom.xml
    strategy:
      fail-fast: false
      matrix:
        arch:
        - x64
        java:
        - 11
        - 17
        os:
        - ubuntu-20.04
        - ubuntu-latest
      max-parallel: 4
name: Java CI with Maven
on:
  repository_dispatch:
    types: trigger-ga___maven_build.yml
